repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.3  # make sure this is the latest version
    hooks:
      # - id: ruff
      #   name: ruff lint
      - id: ruff-format
        name: ruff format
