name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Install project dependencies
        run: |
          pip install .[dev]  # or adjust if you're not using extras like [dev]

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 .

      - name: Lint with black
        run: |
          pip install black
          black --check .

      - name: Run tests with pytest
        run: |
          pip install pytest
          pytest

  # publish:
  #   if: startsWith(github.ref, 'refs/tags/')
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.11'

  #     - name: Build package
  #       run: |
  #         pip install build
  #         python -m build

  #     - name: Publish to PyPI
  #       env:
  #         TWINE_USERNAME: __token__
  #         TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
  #       run: |
  #         pip install twine
  #         twine upload dist/*
